### ISSUE TITLE
Can't enable on new M1 MBP

### ISSUE THREAD

**Issue by jabeler** [UniversalMailer/UniversalMailer#140]
Having trouble getting this to work on a new M1 MBP.

I've tried the 3.0.3 update found at https://github.com/barijaona/UniversalMailer/releases/tag/v/3.0.3 as well as all the old spctl tricks that used to work.

It is working fine on my Intel MBP running macOS 12.0.1, which is strange.

What am I missing?
<img width="372" alt="Screen Shot 2021-11-02 at 12 03 50 PM" src="https://user-images.githubusercontent.com/31429009/139920798-cc747372-ab80-488f-bbeb-d965e0e145a6.png">

<img width="372" alt="Screen Shot 2021-11-02 at 12 03 54 PM" src="https://user-images.githubusercontent.com/31429009/139920803-ad6f0586-c092-4f61-9658-0852799b10c3.png">

**Comment by hashfunktion** [comment]
I can sadly confirm this! 😞 same problem here.
I have tried all the old tricks but no one works this time.

**Comment by jabeler** [comment]
Open to suggestions for how to fix, but I found a workaround for now.

1. Select 'Get Info' on the Mail.app and check the 'Open using Rosetta' box 
2. Install the [original version](https://universalmailer.github.io/UniversalMailer/)
3. Add the correct UUID for 12.0
4. Run

```
sudo spctl --add --label "ApprovedApps" /Library/Mail/Bundles/UniversalMailer.mailbundle
sudo spctl --enable --label "ApprovedApps"
```

5. Done

**Comment by jorgehezd** [comment]
> Open to suggestions for how to fix, but I found a workaround for now.
> 
> 1. Select 'Get Info' on the Mail.app and check the 'Open using Rosetta' box
> 2. Install the [original version](https://universalmailer.github.io/UniversalMailer/)
> 3. Add the correct UUID for 12.0
> 4. Run
> 
> ```
> sudo spctl --add --label "ApprovedApps" /Library/Mail/Bundles/UniversalMailer.mailbundle
> sudo spctl --enable --label "ApprovedApps"
> ```
> 
>  1. Done

Hi @jabeler, 

I have tried to enable the plugin with Rosseta compatibility; I have reinstalled the original version and added, theoretically the UUIDs of macOS 12.0.1, and run the spctl.

However, I have not been successful.

I wonder if the  option private relay on mail has something to do with it?

Anyway, I'll keep trying and I'll be watching @barijaona in case you can help us out here.

Greetings

**Comment by jorgehezd** [comment]
Hi, there is an solution that works for me:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Apparently, the problem is related to the installer package.<br>If I manually copy, through the Finder, the UniversalMailer.mailbundle folder into /Library/Mail/Bundles , I can successfully activate the plugin.</p>&mdash; Barijaona Ramaholimihaso (@barijaona) <a href="https://twitter.com/barijaona/status/1470539545242488837?ref_src=twsrc%5Etfw">December 13, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Could you try with this build ? <a href="https://t.co/mZALaUDlKX">https://t.co/mZALaUDlKX</a></p>&mdash; Barijaona Ramaholimihaso (@barijaona) <a href="https://twitter.com/barijaona/status/1470541294728585216?ref_src=twsrc%5Etfw">December 13, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by jabeler** [comment]
Fix for this has been posted here.

https://github.com/UniversalMailer/UniversalMailer/issues/138#issuecomment-994942939
