### ISSUE TITLE
'Force all files as non-inline' preference only works if no other content in email

### ISSUE THREAD

**Issue by crozynski** [UniversalMailer/UniversalMailer#58]
I work in a production environment supplying png and jpg files to content managers of commercial websites via email. 

Recipients using Windows 10 Mail receive my images inline in the email despite checking the 'Force all files as non-inline' preference in Universal Mailer. When an image arrives inline in Windows Mail its dimensions are changed, which is undesirable.

Interestingly, after testing I've found the preference does work so long as there is no other content in the email other than the attached image. For example:

Test A: Attach jpg to an otherwise empty email in Apple Mail
Test B: Attach jpg to an email with text in it in Apple Mail

Test A arrives in my Windows 10 Mail inbox as an attachment.
Test B arrives in my Windows 10 Mail inbox inline.

I am a (paid) supporter of Universal Mailer and have been using it for years. I am unable to pinpoint the exact date this issue began, although complaints only started around the new year. I upgraded to El Capitan in the new year, so there may be a connection there. I'm currently using Mail 9.2 on El Capitan 10.11.2.

**Comment by UniversalMailer** [comment]
What do you mean by 'empty email'? Does it mean an email without an html signature? If this is the case, the behaviour is somewhat expected, because without it the plugin does not work. In other words:

- if you have a completely empty email (without text and without html signatures) you'll send a plain text email that is not modified by UM. This should be received in Outlook as an attachment (meaning the little icon on the top of the message, just after the sender/subject etc.)

- if you otherwise have an html signature (and text, optionally), the file is sent as an inline attachment, even if the 'force all files as non inline' flag is checked. Is this correct? If so, it's definitely a bug!

**Comment by crozynski** [comment]
Yep, by empty mail I mean without text and without html signatures. 
I am doing exactly what you describe in your second point.
I'm running Windows 10 via Parallels on my Mac here, if you have any troubleshooting ideas I'd be happy to help.

**Comment by UniversalMailer** [comment]
Ok, clear. So there's a problem with inline attachment in the second case, I'll mark this as a bug for now and try to figure out what's wrong with it.

Thanks!

**Comment by AhimsaBjorn** [comment]
I can also confirm that I have been suffering from this bug for around 2 years. It would be very appreciated if it could be fixed in the next release. :)

Whenever image files are sent via email (JPG, PNG, TIF) they display inline with Exchange recipients regardless of setting in Universal Mailer.

**Comment by UniversalMailer** [comment]
V3 is out, should solve the issue
