### ISSUE TITLE
Font Size not being respected.

### ISSUE THREAD

**Issue by owellsjr** [UniversalMailer/UniversalMailer#73]
I'm running Version 3 of Universal Mailer with Mail 10.0 of macOS Sierra Public Beta. I've used this plug-in for years and it's typically very reliable. However, in this configuration I have my Default Font set to Arial 14. But all my messages are being sent as Arial 19. I did some troubleshooting and noticed the following pattern between what I selected on the left and what gets sent on the right:

Arial 14 --> Arial 19
Arial 12 --> Arial 16
Arial 11 --> Arial 15
Arial 10 --> Arial 13

My preferences are set as follows in order to get as close as I can to messages being sent as Arial 14.

<img width="767" alt="untitled" src="https://cloud.githubusercontent.com/assets/20402469/16736394/579d1b0a-4752-11e6-971a-be196711f9c1.png">

**Comment by UniversalMailer** [comment]
Hi,
 since El Capitan Apple changed the way it handles fonts, especially when specified in points (compared to previous OS X versions). My suggestion is to uncheck the 'use points instead of pixels' option, to force pixels for font sizes. If you look at this table: http://reeddesign.co.uk/test/points-pixels.html you'll see your exact matchings between points and pixels sizes.

Explaining the difference between points and pixels is far beyond my current skills in English, but if you're curious you'll find plenty of information about it on the web (just search for 'points vs pixels' or try starting with this page: http://stackoverflow.com/questions/3557260/should-i-use-pt-or-px).

**Comment by owellsjr** [comment]
I'll give this a try. 

O. Wells

**Comment by 3zero2** [comment]
Building up on this: The FAQ suggests to specify using points instead of pixels. Here you suggest to do otherwise on El Capitan and presumably Sierra.

Is the FAQ outdated by any chance?

**Comment by UniversalMailer** [comment]
I think the FAQ still holds: I do suggest to use points instead of pixels for a number of reasons (different screen sizes, different zoom sizes if you use a retina screen etc.), but for this specific use case I think it's better to use pixels, because the expected result is that of retaining a specific font dimension.

Anyway, if you think there's something I can update or modify in the FAQ (or any other page) feel free to suggest it: I'll be happy to update the page with any kind of improvement!
