### ISSUE TITLE
Content-Type: text/markdown

### ISSUE THREAD

**Issue by Crissov** [UniversalMailer/UniversalMailer#77]
My Objective-C skills are very limited, but if I understand the code correctly, I could patch this to make Mail.app send `text/plain` messages (or parts) as `text/markdown` instead, right?

* [Stack Exchange: How can I send emails with Mail.app as text/markdown explicitly?](http://apple.stackexchange.com/questions/241866/how-can-i-send-emails-with-mail-app-as-text-markdown-explicitly)

**Comment by UniversalMailer** [comment]
Hi,
 yes you can replace all text/plain content types with the one you like, although I think this may cause issues with the receiver (e.g. it might discard that part because it doesn't know how to handle it).

Anyway, my approach would be to replace the strings you need in the UMFilter.m file, filterDataByForcingHTML: method, when I build the UMMIMEEntity objects. You should do this after the call to parseHeadersFromString

`        [ne parseHeadersFromString: [plain[0] originalHeaders]];`

so that the original headers are still parsed as expected.

Beware that depending on the type of email you are composing there are a couple of different paths in the code that are taken, be sure to modify all of them.
